name: Build Check ğŸ—ï¸

# When does the robot wake up?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "feature/*" ]

# What does the robot do?
jobs:
  build:
    runs-on: ubuntu-latest # The robot uses a Linux machine

    steps:
    - name: Check out code ğŸ›ï¸
      uses: actions/checkout@v4

    - name: Set up Node.js ğŸŸ¢
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies ğŸ“¦
      run: npm ci

    - name: Try to Build ğŸ› ï¸
      run: npm run build